### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [cottoncoin/cottoncoin#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository
File in question: 
      cottoncoin/LICENSE

**Comment by cottoncoin** [comment]
Hi, we just saw your message. Have asked the dev to rectify the issue ASAP.

**Comment by Iconoclasta** [comment]
Thank you for addressing this issue. I reviewed your repository and everything seems in order. For aesthetic reasons I would suggest to remove one of the two MIT licenses you are now displaying.
I'm closing this issue now, thanks again for your cooperation.
